"""journal's picture id

Revision ID: 2bdf4810b3be
Revises: 5d33d543fd1d
Create Date: 2021-04-18 18:30:02.294195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdf4810b3be'
down_revision = '5d33d543fd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journals', 'pictures', ['picture_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journals', type_='foreignkey')
    op.drop_column('journals', 'picture_id')
    # ### end Alembic commands ###
