"""empty message

Revision ID: 3db01d78e69e
Revises: b2e6d2d51cd1
Create Date: 2021-04-04 17:03:27.079785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3db01d78e69e'
down_revision = 'b2e6d2d51cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('user_routines', sa.Column('amount', mysql.TEXT(), nullable=True))
    op.add_column('user_routines', sa.Column('name', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_routines', 'name')
    op.drop_column('user_routines', 'amount')
    op.drop_column('pictures', 'date')
    # ### end Alembic commands ###
