"""user troubles

Revision ID: 6b73a6101638
Revises: 2bdf4810b3be
Create Date: 2021-05-01 22:09:45.946421

"""
from alembic import op
import sqlalchemy as sa
from libs.database.types import AcleaneTypes


# revision identifiers, used by Alembic.
revision = '6b73a6101638'
down_revision = '2bdf4810b3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('troubles', AcleaneTypes.TextTuple(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'troubles')
    # ### end Alembic commands ###
