"""december_init

Revision ID: b2e6d2d51cd1
Revises: f9468b8c936d
Create Date: 2020-12-01 21:26:54.656607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2e6d2d51cd1'
down_revision = 'f9468b8c936d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('troubles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('email', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('gender', mysql.CHAR(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_google',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', mysql.CHAR(length=50), nullable=False),
    sa.Column('party_name', mysql.TEXT(), nullable=False),
    sa.Column('party_email', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pictures_user_id'), 'pictures', ['user_id'], unique=False)
    op.create_table('routine_amount_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('amount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amount_id'], ['amounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_amount_relations_amount_id'), 'routine_amount_relations', ['amount_id'], unique=False)
    op.create_index(op.f('ix_routine_amount_relations_routine_id'), 'routine_amount_relations', ['routine_id'], unique=False)
    op.create_table('skips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('trouble_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trouble_id'], ['troubles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skips_trouble_id'), 'skips', ['trouble_id'], unique=False)
    op.create_table('user_routines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_routines_routine_id'), 'user_routines', ['routine_id'], unique=False)
    op.create_index(op.f('ix_user_routines_user_id'), 'user_routines', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', mysql.TEXT(), nullable=True),
    sa.Column('third_party_token', mysql.TEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiry', mysql.DATETIME(), nullable=False),
    sa.Column('activated', sa.Integer(), server_default='1', nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_troubles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trouble_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trouble_id'], ['troubles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_troubles_trouble_id'), 'user_troubles', ['trouble_id'], unique=False)
    op.create_index(op.f('ix_user_troubles_user_id'), 'user_troubles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_troubles_user_id'), table_name='user_troubles')
    op.drop_index(op.f('ix_user_troubles_trouble_id'), table_name='user_troubles')
    op.drop_table('user_troubles')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_routines_user_id'), table_name='user_routines')
    op.drop_index(op.f('ix_user_routines_routine_id'), table_name='user_routines')
    op.drop_table('user_routines')
    op.drop_index(op.f('ix_skips_trouble_id'), table_name='skips')
    op.drop_table('skips')
    op.drop_index(op.f('ix_routine_amount_relations_routine_id'), table_name='routine_amount_relations')
    op.drop_index(op.f('ix_routine_amount_relations_amount_id'), table_name='routine_amount_relations')
    op.drop_table('routine_amount_relations')
    op.drop_index(op.f('ix_pictures_user_id'), table_name='pictures')
    op.drop_table('pictures')
    op.drop_table('oauth_google')
    op.drop_table('users')
    op.drop_table('troubles')
    op.drop_table('routines')
    op.drop_table('amounts')
    # ### end Alembic commands ###
