openapi: 3.0.0

info:
  version: '1.0'
  title: 'Laboratory S'
  description: 'Laboratory S API'

servers:
  - description: Local
    url: http://localhost:8000/

paths:
  /:
    $ref: 'rest/health.yaml#/hi'

  # Oauth
#  /oauth/google:
#    $ref: 'rest/oauth.yaml#/google'

  # Users
#  /users/{user_id}:
#    $ref: 'rest/user.yaml#/profile'
#  /users/me:
#    $ref: 'rest/user.yaml#/me'


components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.login_required
#  schemas:

