openapi: 3.0.0

info:
  version: '1.0'
  title: 'Laboratory S'
  description: 'Laboratory S API'

servers:
  - description: Local
    url: http://localhost:8000/

paths:
  /:
    $ref: 'rest/health.yaml#/hi'

  # Image
  /image:
    $ref: 'rest/picture.yaml#/picture'
  /image/{date}:
    $ref: 'rest/picture.yaml#/picture_by_date'

  # Oauth
  /oauth/google:
    $ref: 'rest/oauth.yaml#/google'

  # Users
#  /users/{user_id}:
#    $ref: 'rest/user.yaml#/profile'
  /users/me:
    $ref: 'rest/user.yaml#/me'
  /users/name/{name}:
    $ref: 'rest/user.yaml#/name'

  # Routines
  /routines:
    $ref: 'rest/routine.yaml#/routine'
  /routines/user:
    $ref: 'rest/routine.yaml#/user_routine'
  /routines/user/{user_routine_id}:
    $ref: 'rest/routine.yaml#/user_routine_by_id'

  # Journals
  /journals:
    $ref: 'rest/journal.yaml#/journal'
  /journals/{journal_id}:
    $ref: 'rest/journal.yaml#/journal_by_id'


components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      x-bearerInfoFunc: libs.route.login_required.login_required
  schemas:
    user:
      $ref: 'models/user.yaml#/user'
